### ISSUE TITLE
Parameter 'commandLine' cannot be null or empty.

### ISSUE THREAD

**Issue by kstalyarova** [Azure/setup-helm#10]
I tried to setup version of Helm 2.14.3 and know helm version:

```
  deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Setup helm 
        uses: azure/setup-helm@v1
        with:
          version: 'v2.14.3' # default is latest stable
        id: install

      - run: |
          helm version --client
```
But I got the following error:
![image](https://user-images.githubusercontent.com/60093638/76864659-8549fb00-6872-11ea-898f-49ec63ff32e5.png)

Could you tell me what's wrong?
