### ISSUE TITLE
Wrong version used after installation

### ISSUE THREAD

**Issue by shashankbarsin** [Azure/setup-helm#2]
The following YAML snippet is expected to result in Helm 3 being setup for usage as setup-helm action installs latest version (3) by default if version input is left unspecified. While setup-helm installs Helm 3 in tool cache, running helm version shows that version 2 is the one picked up by running helm command

```yaml
- uses: azure/setup-helm@v1
- run: |
    helm version
```
