### ISSUE TITLE
Unexpected HTTP response: 403 with v2

### ISSUE THREAD

**Issue by gruebel** [Azure/setup-helm#59]
we are getting permission denied errors on `macos-latest` runner when using the new v2 version.

```shell
Download action repository 'azure/setup-helm@v2.0' (SHA:a517f2ff6560563a369e16ca7c7d136b6164423f)
```

```shell
Run azure/setup-helm@v2.0
  with:
    version: latest
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.8.12/x64
Error: Error: Unexpected HTTP response: 403
```

a failed run can be seen here https://github.com/bridgecrewio/checkov/runs/5008556832

**Comment by qpetraroia** [comment]
Hey @gruebel, 

we are looking into it

**Comment by gruebel** [comment]
@qpetraroia any update so far?

**Comment by OliverMKing** [comment]
This seems to be working in v2.1. I'm unsure why this error occurred because there's no clear difference between v2.0 and v2.1 that would impact this issue.

**Comment by gruebel** [comment]
@OliverMKing sadly it still fails https://github.com/bridgecrewio/checkov/runs/6496731470?check_suite_focus=true

Current workflow steps
```yaml
  integration-tests:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@v3
      - uses: azure/setup-helm@217bf70cbd2e930ba2e81ba7e1de2f7faecc42ba  # v2
```
