### ISSUE TITLE
Warning: Unexpected input(s) 'id', valid inputs are ['version', 'token']

### ISSUE THREAD

**Issue by ryan-efendy** [Azure/setup-helm#60]
How to get rid of this warning:

![image](https://user-images.githubusercontent.com/12979345/152048852-4ee3f197-5a14-45bd-9ec2-1f75c8b05262.png)

We followed this example:
![image](https://user-images.githubusercontent.com/12979345/152049000-422f7ceb-f734-48f8-8a12-46bb49e4777a.png)

**Comment by hairmare** [comment]
The `id` is not part of `with`. It should look like this:

```yaml
- uses: azure/setup-helm@v1
  id: install
  with:
    version: 3.6.3
    token: ***
```

instead of this:

```yaml
- uses: azure/setup-helm@v1
  with:
    version: 3.6.3
    id: install
    token: ***
```

I tend to put the `id` field right after `uses` or `name` because i think it improves readability.
