### ISSUE TITLE
Unable to install a particular version

### ISSUE THREAD

**Issue by zCHIP** [Azure/setup-helm#9]
I tried to specify a particular version of Helm 3 like
```yaml
jobs:
  job:
    steps:
      - name: Install Helm 3
        uses: azure/setup-helm@v1
        with:
          version: 3.1.1
```
and got the following error:
```
##[error]Error: Failed to download Helm from location  https://get.helm.sh/helm-3.1.1-linux-amd64.zip
```

Using `latest` worked well.
