### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by floralatin** [Azure/setup-helm#96]
### What happened?

azure/setup-helm@v3 to install helm in GitHub action

Error while fetching latest Helm release: Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set. It must be set on either `env:` or `with:`. See https://github.com/octokit/auth-action.js#createactionauth. Using default version v3.9.0

### Version

- [X] I am using the latest version

### Runner

- name: Setup Helm         uses: azure/setup-helm@v3

### Relevant log output

Error while fetching latest Helm release: Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set. It must be set on either `env:` or `with:`. See https://github.com/octokit/auth-action.js#createactionauth. Using default version v3.9.0

**Comment by bakito** [comment]
@floralatin  You have to set this in you workflow.
```
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
